---
title: "Gossip Simulator Plots"
author: "Kadir Korkmaz"
date: "9/10/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data
```{r, echo=FALSE}

library(jsonlite)

#https://github.com/jeroen/jsonlite/issues/59

gossip_df <- stream_in( file("../cmd/sim_fanout8_datachunk48_experiment500.out",open="r") )
#gossip_df <- stream_in( file("../cmd/simulation_fanout8_datachunk48_experiment_200.out",open="r") )

gossip_df$FailurePercent <- (gossip_df$FailureCount * 100) / gossip_df$ExperimentCount #/ 100


gossip_df$AverageDeliveryPercent <- gossip_df$AverageDeliveryPercent * 100
```

\newpage
## Plots
```{r, echo=FALSE, fig.width=5, fig.height=7}

library(dplyr)
library(reshape)
library(ggplot2)

#https://github.com/jeroen/jsonlite/issues/59
filtered_df <- gossip_df %>% select(ExperimentType, FaultyNodePercent, AverageDeliveryPercent,FailurePercent, AverageReceivedCount, AverageForwardCount )

filtered_df <- filtered_df %>% mutate(ExperimentType = replace(ExperimentType, ExperimentType == "ida", "IDA-Gossip"))
filtered_df <- filtered_df %>% mutate(ExperimentType = replace(ExperimentType, ExperimentType == "classic", "Classic"))


melted_df <- melt(filtered_df, id=c("ExperimentType","FaultyNodePercent"))




p <- ggplot(melted_df, aes(x=FaultyNodePercent, y=value,  group=ExperimentType, color=ExperimentType, )) +
      geom_line()+
      #geom_point()+
      expand_limits(y = 0) +
      labs(color='Type') +
      theme_bw()+
      theme(legend.position="top") +
      ylab(NULL) +
      xlab("Fraction of Faulty Nodes") +
      theme(strip.background = element_blank(), # remove the background
          strip.placement = "outside", legend.title=element_text(size=8), legend.margin=margin(0,-0,-6,0))

#, switch = "y"
p <- p + facet_grid(variable ~ ., scales = "free_y" , labeller = as_labeller(
      c(AverageDeliveryPercent = "Avg. Delivery Percent", FailurePercent = "Avg. Diss. Failure", AverageReceivedCount= "Avg. Rec. Chunk Count", AverageForwardCount = "Avg. Deliv. Chunk Count"))
  ) + theme(plot.margin = margin(0,0,0,0, "cm"))

p

ggsave("simulation-results.pdf", p)


```

\newpage
## Delivery Percent Diff
```{r, echo=FALSE, fig.width=5, fig.height=6}

library(dplyr)
library(ggplot2)


ida_df <- gossip_df %>%  select(ExperimentType, FaultyNodePercent, AverageDeliveryPercent, FailurePercent) %>% filter(ExperimentType == "ida") 
classic_df <- gossip_df %>%  select(ExperimentType, FaultyNodePercent, AverageDeliveryPercent, FailurePercent) %>% filter(ExperimentType == "classic")

joined_df <- inner_join(ida_df, classic_df, by="FaultyNodePercent")

joined_df$DeliveryDiff <- joined_df$AverageDeliveryPercent.x -  joined_df$AverageDeliveryPercent.y

joined_df$FailureDiff <- joined_df$FailurePercent.x -  joined_df$FailurePercent.y

ggplot(data=joined_df, aes(x=FaultyNodePercent, y=DeliveryDiff, group=1)) +
  geom_line()

```




\newpage
## Failure Percent Diff
```{r, echo=FALSE, fig.width=5, fig.height=6}

library(dplyr)
library(ggplot2)

ggplot(data=joined_df, aes(x=FaultyNodePercent, y=FailureDiff, group=1)) +
  geom_line()
```



